require conf/distro/openbmc-phosphor.conf
require conf/distro/include/phosphor-isolation.inc

CANOPY_VERSION ?= "2026.04"
DISTRO = "canopy"
DISTRO_NAME = "CanopyBMC (based on Phosphor OpenBMC)"
DISTRO_VERSION = "canopy-${CANOPY_VERSION}"
EXTENDED_VERSION = "${DISTRO_VERSION}"
DISTROOVERRIDES .= ":canopy"

# Possible values: "dev", "release"
CANOPY_CONFIG ?= "release"
OVERRIDES .= ":${CANOPY_CONFIG}:"

IMAGE_FEATURES:append = " allow-root-login"
