[Unit]
After=xyz.openbmc_project.EntityManager.service
After=xyz.openbmc_project.Inventory.Manager.service
Requires=xyz.openbmc_project.Inventory.Manager.service
After=mapper-wait@-xyz-openbmc_project-inventory.service
Wants=mapper-wait@-xyz-openbmc_project-inventory.service
