BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "canopy-aspeed-layer"
BBFILE_PATTERN_canopy-aspeed-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_canopy-aspeed-layer = "12"
LAYERSERIES_COMPAT_canopy-aspeed-layer = "wrynose whinlatter"
