# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "kommando-ipmi-card-layer"
BBFILE_PATTERN_kommando-ipmi-card-layer = "^${LAYERDIR}/"
BBFILE_PRIORITY_kommando-ipmi-card-layer = "6"

LAYERDEPENDS_kommando-ipmi-card-layer = "core"
LAYERSERIES_COMPAT_kommando-ipmi-card-layer = "wrynose whinlatter"
