---
name: hpe-proliant-g11 Build

on:
  push:
    branches:
      - main
    paths:
      - 'openbmc/**'
      - 'meta-canopy/**'
      - '.github/**'
      - '.firmwareci/**'
  pull_request:
    branches:
      - main
    paths:
      - 'openbmc/**'
      - 'meta-canopy/**'
      - '.github/**'
      - '.firmwareci/**'
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, Hydra, Large]
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build
        uses: ./.github/actions/build
        with:
          board: hpe-proliant-g11
          signing-key: ${{ secrets.HPE_9E_SIGNING_KEY }}

  firmwareci:
    runs-on: [self-hosted, Hydra, Large]
    needs: build
    steps:
      - name: Download firmware image
        uses: actions/download-artifact@v8
        with:
          name: obmc-phosphor-image-hpe-proliant-g11

      - name: Upload to FirmwareCI
        uses: docker://firmwareci/action:v5.2
        with:
          TOKEN: ${{ secrets.FWCI_TOKEN }}
          WORKFLOW_NAME: ${{ secrets.FWCI_WORKFLOW_NAME }}
          COMMIT_HASH: ${{ github.sha }}
          BINARIES: Binary=obmc-phosphor-image-hpe-proliant-g11.GXP2loader-t282-t288-sgn00.static.mtd
          GITHUB_INSTALLATION_ID: ${{ secrets.FWCI_GITHUB_INSTALLATION_ID }}

  firmwareci-main:
    runs-on: [self-hosted, Hydra, Large]
    needs: build
    if: github.event_name == 'push'
    steps:
      - name: Download firmware image
        uses: actions/download-artifact@v8
        with:
          name: obmc-phosphor-image-hpe-proliant-g11

      - name: Upload to FirmwareCI
        uses: docker://firmwareci/action:v5.2
        with:
          TOKEN: ${{ secrets.FWCI_TOKEN }}
          WORKFLOW_NAME: ${{ secrets.FWCI_MAIN_WORKFLOW_NAME }}
          COMMIT_HASH: ${{ github.sha }}
          BINARIES: Binary=obmc-phosphor-image-hpe-proliant-g11.GXP2loader-t282-t288-sgn00.static.mtd
          GITHUB_INSTALLATION_ID: ${{ secrets.FWCI_GITHUB_INSTALLATION_ID }}
